version: '3.3'
# uncomment these lines if you are using volumes instead of bind mounts
#volumes:
#  cosmos:
#    external: true
#  adguard-config:
#    external: true
services:
  cosmos-cert-extractor:
    image: 'waschinski/cosmos-cert-extractor:latest'
    container_name: cosmos-cert-extractor
    restart: always
    volumes:
      - /var/lib/cosmos:/input:ro
      #- cosmos:/input:ro # use this line instead if you use a volume
      - /my/own/adguardconfdir:/output
      #- adguard-config:/output # use this line instead if you use a volume
    environment:
      - CERT_SUBFOLDER=/certs